// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadXSD(arg1:string):Promise<main.LoadResult>;

export function OpenFileDialog():Promise<string>;
